version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
  commit-message:
      prefix: "chore(npm)"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  commit-message:
      prefix: "chore(github-actions)"
  open-pull-requests-limit: 10
